# Generated by Django 4.0.2 on 2022-02-18 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_name', models.CharField(max_length=100)),
                ('cast_age', models.IntegerField()),
                ('cast_movie_name', models.CharField(max_length=150)),
                ('cast_img', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.movie')),
            ],
        ),
    ]
