# Generated by Django 4.0.2 on 2022-02-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('released_date', models.DateField()),
                ('movie_time', models.CharField(max_length=100)),
                ('movie_type', models.CharField(max_length=140)),
                ('released_status', models.BooleanField(default=False)),
                ('budget', models.IntegerField()),
                ('revenue', models.IntegerField()),
                ('video_trailer', models.FileField(null=True, upload_to='videos/%Y/%m/%d')),
                ('movie_languages', models.TextField()),
                ('tags', models.TextField()),
                ('main_img', models.FileField(upload_to='images/%Y/%m/%d')),
                ('overview', models.TextField(blank=True)),
                ('img1', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('img2', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('img3', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('img4', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('img5', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('user_watched', models.IntegerField()),
            ],
        ),
    ]
