# Generated by Django 4.0.2 on 2022-02-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_trailer',
            field=models.TextField(default='https://www.youtube.com/embed/KAE5ymVLmZg'),
        ),
    ]
