# Generated by Django 4.0.2 on 2022-03-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_movie_video_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='main_img',
            field=models.TextField(blank=True, default='https://i.postimg.cc/85PL5KF0/avengers.jpg'),
        ),
    ]
