# Generated by Django 4.0.2 on 2022-03-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_movie_main_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img1',
            field=models.TextField(blank=True, default='https://i.postimg.cc/85PL5KF0/avengers.jpg'),
        ),
    ]
